# permissions for end users to view awss3secrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: awss3secret-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: s3-config-operator
    app.kubernetes.io/part-of: s3-config-operator
    app.kubernetes.io/managed-by: kustomize
  name: awss3secret-viewer-role
rules:
- apiGroups:
  - aws.example.com
  resources:
  - awss3secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - aws.example.com
  resources:
  - awss3secrets/status
  verbs:
  - get
