---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aws.example.com
  resources:
  - awss3secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aws.example.com
  resources:
  - awss3secrets/finalizers
  verbs:
  - update
- apiGroups:
  - aws.example.com
  resources:
  - awss3secrets/status
  verbs:
  - get
  - patch
  - update
