apiVersion: aws.example.com/v1beta1
kind: AwsS3Secret
metadata:
  labels:
    app.kubernetes.io/name: awss3secret
    app.kubernetes.io/instance: awss3secret-sample
    app.kubernetes.io/part-of: s3-config-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: s3-config-operator
  name: awss3secret-sample
spec:
  # TODO(user): Add fields here
  secretName: "dota"
  s3url: "s3://secret-operator/lol.txt"
